//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kapasitematik_TakimOmru_v3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int NoteID { get; set; }
        public string NoteHeader { get; set; }
        public string NoteDescription { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> FkPieceID { get; set; }
        public Nullable<int> FkSubPieceID { get; set; }
        public Nullable<int> FkUserID { get; set; }
        public Nullable<bool> Type { get; set; }
    
        public virtual Piece Piece { get; set; }
        public virtual SubPiece SubPiece { get; set; }
        public virtual User User { get; set; }
    }
}
