//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kapasitematik_TakimOmru_v3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotificationID { get; set; }
        public string Notification_Description { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<System.DateTime> Notification_Date { get; set; }
        public Nullable<int> FKUserId { get; set; }
        public Nullable<int> FKNotificationSettingID { get; set; }
    
        public virtual User User { get; set; }
    }
}
