//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kapasitematik_TakimOmru_v3
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class SubPiece
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubPiece()
        {
            this.Detail = new HashSet<Detail>();
            this.Notes = new HashSet<Note>();
        }
    
        public int SubPieceID { get; set; }
        public string SubPieceName { get; set; }
        public Nullable<int> ToolLife { get; set; }
        public Nullable<int> Now { get; set; }
        public Nullable<int> FKPieceID { get; set; }
        public Nullable<int> FKUserID { get; set; }

        [DisplayName("Tipi")]
        public Nullable<bool> Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detail> Detail { get; set; }
        public virtual Piece Piece { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note> Notes { get; set; }
    }
}
