//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kapasitematik_TakimOmru_v3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TakimOmruDBEntities : DbContext
    {
        public TakimOmruDBEntities()
            : base("name=TakimOmruDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Detail> Detail { get; set; }
        public virtual DbSet<Piece> Piece { get; set; }
        public virtual DbSet<SubPiece> SubPiece { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Notification> Notification { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<PimsunDeviceNo> PimsunDeviceNoes { get; set; }
    
        public virtual ObjectResult<Notification> SP_Notification_Update_Counter_v1(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Notification>("SP_Notification_Update_Counter_v1", userIdParameter);
        }
    
        public virtual ObjectResult<Notification> SP_Notification_Update_Counter_v1(Nullable<int> userId, MergeOption mergeOption)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Notification>("SP_Notification_Update_Counter_v1", mergeOption, userIdParameter);
        }
    }
}
